export let kanbanDataCheck = [
  {
    id: 1,
    title: "Fix login page bug",
    description: "Refactor the old codebase.",
    startDate: "01-12-2024",
    endDate: "02-12-2024",
    actualHours: 4,
    estimatedHours: 5,
    status: "Open",
    resourceName: "Nikhil Shah",
    resourceImgUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTA78Na63ws7B7EAWYgTr9BxhX_Z8oLa1nvOA&s",
  },
  {
    id: 2,
    title: "Improve performance on homepage",
    description: "Analyze stored procedures.",
    startDate: "03-12-2024",
    endDate: "05-12-2024",
    actualHours: 9,
    estimatedHours: 8,
    status: "InProgress",
    resourceName: "Robin Chacko",
    resourceImgUrl: "https://i.pravatar.cc/150?img=57",
  },
  {
    id: 3,
    title: "Design landing page",
    description: "Coordinate with the frontend team.",
    startDate: "06-12-2024",
    endDate: "07-12-2024",
    actualHours: 7,
    estimatedHours: 6,
    status: "Close",
    resourceName: "Sanjeev Thakur",
    resourceImgUrl: "https://i.pravatar.cc/300?img=58",
  },
  {
    id: 4,
    title: "Implement search functionality",
    description: "Prepare a report on the findings.",
    startDate: "08-12-2024",
    endDate: "10-12-2024",
    actualHours: 6,
    estimatedHours: 7,
    status: "Testing",
    resourceName: "Vinod Yadav",
    resourceImgUrl: "https://i.pravatar.cc/300?img=65",
  },
  {
    id: 5,
    title: "Upgrade database schema",
    description: "Discuss with the team lead.",
    startDate: "11-12-2024",
    endDate: "12-12-2024",
    actualHours: 5,
    estimatedHours: 4,
    status: "Open",
    resourceName: "Vikas Shingh",
    resourceImgUrl: "https://i.pravatar.cc/300?img=54",
  },
  {
    id: 6,
    title: "Code review for authentication module",
    description: "Review and merge pull requests.",
    startDate: "13-12-2024",
    endDate: "14-12-2024",
    actualHours: 7,
    estimatedHours: 5,
    status: "InProgress",
    resourceName: "Nikhil Shah",
    resourceImgUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTA78Na63ws7B7EAWYgTr9BxhX_Z8oLa1nvOA&s",
  },
  {
    id: 7,
    title: "Optimize API calls",
    description: "Test across multiple browsers.",
    startDate: "15-12-2024",
    endDate: "16-12-2024",
    actualHours: 6,
    estimatedHours: 8,
    status: "Close",
    resourceName: "Robin Chacko",
    resourceImgUrl: "https://i.pravatar.cc/150?img=57",
  },
  {
    id: 8,
    title: "Refactor user profile page",
    description: "Optimize loading time.",
    startDate: "17-12-2024",
    endDate: "18-12-2024",
    actualHours: 6,
    estimatedHours: 6,
    status: "Testing",
    resourceName: "Sanjeev Thakur",
    resourceImgUrl: "https://i.pravatar.cc/300?img=58",
  },
  {
    id: 9,
    title: "Test payment gateway integration",
    description: "Consult with the security team.",
    startDate: "19-12-2024",
    endDate: "20-12-2024",
    actualHours: 7,
    estimatedHours: 8,
    status: "Open",
    resourceName: "Vinod Yadav",
    resourceImgUrl: "https://i.pravatar.cc/300?img=65",
  },
  {
    id: 10,
    title: "Update documentation",
    description: "Implement suggested changes.",
    startDate: "21-12-2024",
    endDate: "22-12-2024",
    actualHours: 5,
    estimatedHours: 7,
    status: "InProgress",
    resourceName: "Vikas Shingh",
    resourceImgUrl: "https://i.pravatar.cc/300?img=54",
  },
  {
    id: 11,
    title: "Deploy staging server",
    description: "Validate user input fields.",
    startDate: "23-12-2024",
    endDate: "24-12-2024",
    actualHours: 10,
    estimatedHours: 8,
    status: "Close",
    resourceName: "Nikhil Shah",
    resourceImgUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTA78Na63ws7B7EAWYgTr9BxhX_Z8oLa1nvOA&s",
  },
  {
    id: 12,
    title: "Fix CSS issues in mobile view",
    description: "Set up a new database instance.",
    startDate: "25-12-2024",
    endDate: "26-12-2024",
    actualHours: 4,
    estimatedHours: 5,
    status: "Testing",
    resourceName: "Robin Chacko",
    resourceImgUrl: "https://i.pravatar.cc/150?img=57",
  },
  {
    id: 13,
    title: "Develop new user onboarding flow",
    description: "Update dependencies.",
    startDate: "27-12-2024",
    endDate: "28-12-2024",
    actualHours: 9,
    estimatedHours: 6,
    status: "Open",
    resourceName: "Sanjeev Thakur",
    resourceImgUrl: "https://i.pravatar.cc/300?img=58",
  },
  {
    id: 14,
    title: "Set up continuous integration",
    description: "Implement new feature requests.",
    startDate: "29-12-2024",
    endDate: "30-12-2024",
    actualHours: 9,
    estimatedHours: 7,
    status: "InProgress",
    resourceName: "Vinod Yadav",
    resourceImgUrl: "https://i.pravatar.cc/300?img=65",
  },
  {
    id: 15,
    title: "Analyze server logs for errors",
    description: "Run unit tests and validate.",
    startDate: "31-12-2024",
    endDate: "01-01-2025",
    actualHours: 7,
    estimatedHours: 8,
    status: "Testing",
    resourceName: "Vikas Shingh",
    resourceImgUrl: "https://i.pravatar.cc/300?img=54",
  },
  {
    id: 16,
    title: "Enhance security protocols",
    description: "Deploy the updated version.",
    startDate: "02-01-2025",
    endDate: "03-01-2025",
    actualHours: 7,
    estimatedHours: 6,
    status: "Close",
    resourceName: "Nikhil Shah",
    resourceImgUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTA78Na63ws7B7EAWYgTr9BxhX_Z8oLa1nvOA&s",
  },
  {
    id: 17,
    title: "Create test cases for new features",
    description: "Draft user guide and manuals.",
    startDate: "04-01-2025",
    endDate: "05-01-2025",
    actualHours: 9,
    estimatedHours: 7,
    status: "Open",
    resourceName: "Robin Chacko",
    resourceImgUrl: "https://i.pravatar.cc/150?img=57",
  },
  {
    id: 18,
    title: "Fix deployment script errors",
    description: "Implement feedback from QA team.",
    startDate: "06-01-2025",
    endDate: "07-01-2025",
    actualHours: 4,
    estimatedHours: 5,
    status: "InProgress",
    resourceName: "Sanjeev Thakur",
    resourceImgUrl: "https://i.pravatar.cc/300?img=58",
  },
  {
    id: 19,
    title: "Conduct user testing for new features",
    description: "Analyze test results and report.",
    startDate: "08-01-2025",
    endDate: "09-01-2025",
    actualHours: 7,
    estimatedHours: 6,
    status: "Testing",
    resourceName: "Vinod Yadav",
    resourceImgUrl: "https://i.pravatar.cc/300?img=65",
  },
  {
    id: 20,
    title: "Prepare release notes for new version",
    description: "Document all changes and updates.",
    startDate: "10-01-2025",
    endDate: "11-01-2025",
    actualHours: 3,
    estimatedHours: 4,
    status: "Close",
    resourceName: "Vikas Shingh",
    resourceImgUrl: "https://i.pravatar.cc/300?img=54",
  },
];
